console.log('Heloo World');
console.log(2+4+6);
console.log("I am a genious");
let myName = 'Nishant';
console.log(myName);
let myHtml = '<h1> This is my world </h1>';
console.log(myHtml.toUpperCase());
console.log(myHtml.indexOf('>'));
console.log(myHtml.lastIndexOf('s'));
console.log(myHtml.lastIndexOf('<'));
console.log(myHtml.charAt(3));
console.log(myHtml.length);
console.log(myHtml.substring(0,6));
console.log(myHtml.endsWith('world'));
console.log(myHtml.slice(-4));
console.log(myHtml.slice(0,4));
console.log(myHtml.split(' '));
console.log(myHtml.replace('This','That'));
let fruit1 = 'Orange';
let fruit2 = 'Apple';
let myFavourite = `Hello World my favourite fruite is ${fruit1} and ${fruit2} keeps doctor away`;
console.log(myFavourite);